services:
  - type: web
    name: sora-video-stitcher-api
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PUBLIC_URL
        sync: false
      - key: SORA_API_KEY
        sync: false
      - key: SORA_API_BASE_URL
        value: https://api.kie.ai/api/v1
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_TABLE_NAME
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: JOB_TIMEOUT
        value: 600000
    autoDeploy: true
