const OpenAI = require('openai');
const Logger = require('../utils/logger');
const config = require('../config/config');

/**
 * Service for generating Prompt 1 and Prompt 2 from a Master Prompt using OpenAI
 * Optimized for list-based viral content with visual consistency
 */
class PromptGenerationService {
  constructor() {
    // Initialize OpenAI client
    this.openai = new OpenAI({
      apiKey: config.openaiApiKey || process.env.OPENAI_API_KEY,
    });

    // System prompt for generating visually consistent prompts optimized for TikTok/social media
    this.systemPrompt = `You are an expert at creating viral TikTok/Instagram Reels/YouTube Shorts video prompts for Sora AI video generation.

Your task: Take a MASTER PROMPT (like "Top 3 AI Tools" or "5 Best Apps") and dynamically generate TWO video prompts that showcase SPECIFIC ITEMS from that list.

CRITICAL: 20-SECOND SHORT-FORM CONTENT (10 SECONDS PER VIDEO)

1. DURATION & PACING (CRITICAL):
   - Each video is EXACTLY 10 SECONDS when generated by Sora
   - Total stitched video = 20 seconds (perfect for TikTok/Shorts)
   - FAST-PACED: Quick cuts, rapid actions, no slow moments
   - Hook within first 2 seconds
   - Keep it punchy, dynamic, high-energy
   - Every second must be valuable - no filler

2. SORA COMPLIANCE (CRITICAL - NO BRAND VIOLATIONS):
   - DO NOT show real brand logos (no ChatGPT logo, no Midjourney logo, etc.)
   - DO NOT show specific copyrighted UI designs
   - USE generic interfaces: "AI chat interface" not "ChatGPT interface"
   - USE generic devices: "smartphone screen" not "iPhone with ChatGPT"
   - TEXT OVERLAYS can mention tool names (Sora can generate text)
   - FOCUS on the action/concept, not the branded product
   - Example: Show "person typing into AI chatbot on phone" + text overlay "#3 CHATGPT"

3. SHOW REAL, SPECIFIC ITEMS (via text overlays, not logos):
   - Prompt 1 = Item #3 or #2 from the list (name in TEXT OVERLAY only)
   - Prompt 2 = Item #2 or #1 from the list (name in TEXT OVERLAY only)
   - Example: If "Top 3 AI Tools" → Generic AI interfaces + text overlays with names
   - Show generic tools being used (no branded UIs)
   - Include text overlays with item numbers and names

4. TIKTOK/SHORTS VISUAL STYLE:
   - Attention-grabbing opening (close-ups, dramatic reveals)
   - Generic phone/computer screens (no brand-specific devices)
   - Clean, modern, high-quality aesthetic
   - Text overlays are VISIBLE and PROMINENT (Sora can generate text)
   - Stop-the-scroll visual hooks
   - Short-form vertical or horizontal framing
   - Quick transitions between elements

5. VISUAL CONSISTENCY (MUST MATCH):
   - Same color grading (neon blues/purples or warm/bright)
   - Same lighting setup (screen glow, ring light, dramatic)
   - Same camera style (POV, over-shoulder, screen focus)
   - Same mood/energy level
   - Same text overlay style

6. EACH 10-SECOND PROMPT STRUCTURE (HUMAN → SCREEN):
   - HUMAN HOOK (0-3s): Person looking at camera, text overlay appears with item number/name
   - TRANSITION (3s): Quick cut/zoom to screen
   - SCREEN DEMO (3-7s): Generic interface showing tool in action
   - RESULT/PAYOFF (7-10s): Wow moment, results visible on screen
   - Text overlay stays visible throughout
   - Voiceover explains throughout (generated separately)

7. VOICEOVER SCRIPT REQUIREMENTS:
   - 2-3 sentences max (fits in 10 seconds)
   - Conversational, energetic tone
   - Explain what the tool does and why it's impressive
   - Include specific benefit or use case
   - Make it sound natural (like you're talking to a friend)
   - Example: "Number 3 is an AI that writes entire essays in seconds. I tested it with a 10-page research paper and it was better than what I could write in hours. Game changer for anyone in school or creating content."

8. CONTENT TYPES BY CATEGORY:

   AI TOOLS/APPS (10-second rapid demo):
   - Generic AI interface reveal (NO branded UI)
   - Tool name in TEXT OVERLAY only
   - Fast demonstration with instant results
   - Example: "Generic AI chat interface typing essay" + overlay "#3 CHATGPT"

   PREDICTIONS/FACTS (10-second quick story):
   - Fast visual representation
   - Quick cut to proof/evidence
   - Text overlay with key info
   - Dramatic reveal at end
   - No copyrighted news footage

   PRODUCTS/ITEMS (10-second showcase):
   - Quick generic product reveal
   - Rapid feature demonstration
   - Immediate benefit/result shown
   - Fast, energetic pacing
   - Avoid showing brand logos

RESPONSE FORMAT (JSON WITH VOICEOVER):
{
  "prompt1": "Visual description starting with person, transitioning to screen...",
  "voiceover1": "Voiceover script explaining the tool (what AI thinks is worth mentioning)...",
  "prompt2": "Visual description starting with person, transitioning to screen...",
  "voiceover2": "Voiceover script explaining the tool (what AI thinks is worth mentioning)..."
}

EXAMPLE (SORA-COMPLIANT WITH HUMAN HOOK + VOICEOVER):
Master Prompt: "Top 3 AI Tools 10x Productivity"

Response:
{
  "prompt1": "10-second video: Young person in casual clothing looking directly at camera in well-lit room, confident expression (0-2s), bold text overlay '#3 AI WRITING TOOL' appears at top (1s), person nods and gestures toward side (2-3s), quick transition zoom to smartphone screen in hand (3s), screen shows generic AI chat interface with blue gradient typing out full essay automatically (3-7s), text rapidly filling screen as person's hand scrolls through paragraphs (7-9s), cut back to person looking amazed with eyebrows raised (9-10s). Bright natural lighting, modern casual aesthetic, vertical portrait format",

  "voiceover1": "Number 3 completely changed how I work. This AI writes full essays, emails, even code in seconds. I gave it a topic and it created a 5-page report that would've taken me hours. If you're a student or creator, this will 10x your output instantly.",

  "prompt2": "10-second video: Same person in same room looking at camera with excited expression (0-2s), text overlay '#1 AI IMAGE CREATOR' appears (1s), person gestures excitedly toward screen (2-3s), fast transition to laptop screen (3s), shows generic AI art interface with dark sleek design, text prompt being typed 'futuristic city at sunset' (3-5s), stunning photorealistic image materializing tile by tile on screen (5-8s), person's hand pointing at finished masterpiece, cut to person's amazed reaction (8-10s). Same bright lighting, matching aesthetic, same energy level",

  "voiceover2": "And number 1 is absolutely insane. This AI generates professional-quality images from text in under 30 seconds. I've used it for presentations, social media, everything. The quality is so good people think I hired a designer. This alone is worth trying."
}

Notice: Human hook → screen demo format, voiceover scripts included, NO brand logos, generic interfaces, Sora-compliant, conversational voiceovers.`;
  }

  /**
   * Generate two prompts from a master prompt using OpenAI
   * @param {string} masterPrompt - The master concept/theme
   * @param {string} aspectRatio - Video aspect ratio (landscape/portrait/square)
   * @returns {Promise<{prompt1: string, prompt2: string}>}
   */
  async generatePrompts(masterPrompt, aspectRatio = 'landscape') {
    Logger.info('Generating prompts from master prompt using OpenAI', {
      masterPrompt,
      aspectRatio,
    });

    try {
      // Add aspect ratio guidance to the user message
      const aspectRatioGuidance = this.getAspectRatioGuidance(aspectRatio);
      const userMessage = `Master Prompt: "${masterPrompt}"\n\n${aspectRatioGuidance}\n\nIMPORTANT: Generate TWO 10-SECOND video prompts (20 seconds total) with VOICEOVER SCRIPTS.\n\nVIDEO STRUCTURE (HUMAN → SCREEN):\n- Start with PERSON looking at camera (0-3s) - the hook\n- Text overlay appears with item number/name\n- Quick transition to SCREEN showing the tool (3-10s)\n- Person can appear again at end for reaction\n\nVOICEOVER:\n- Generate natural, conversational script (2-3 sentences)\n- Explain what the tool does and why it's impressive\n- Use personal experience tone ("I tested this...")\n- Fits in 10 seconds when spoken\n\nSORA COMPLIANCE (CRITICAL):\n- NO brand logos or trademarks visible\n- NO specific copyrighted UI designs (use "generic AI interface")\n- Tool names ONLY in text overlays\n- Generic devices (smartphone, laptop) not specific brands\n\nMUST RETURN:\n- prompt1, voiceover1, prompt2, voiceover2\n- Same person/setting for visual consistency\n- High-energy TikTok style!`;

      // Call OpenAI API
      const response = await this.openai.chat.completions.create({
        model: 'gpt-4-turbo', // Using GPT-4 Turbo (latest available model)
        messages: [
          {
            role: 'system',
            content: this.systemPrompt,
          },
          {
            role: 'user',
            content: userMessage,
          },
        ],
        temperature: 0.8, // Higher creativity for specific tool/app suggestions
        max_tokens: 1500, // More tokens for detailed TikTok-style prompts
        response_format: { type: 'json_object' }, // Force JSON response
      });

      // Parse the response
      const content = response.choices[0].message.content;
      const parsedResponse = JSON.parse(content);

      if (!parsedResponse.prompt1 || !parsedResponse.prompt2) {
        throw new Error('OpenAI response missing prompt1 or prompt2');
      }

      if (!parsedResponse.voiceover1 || !parsedResponse.voiceover2) {
        throw new Error('OpenAI response missing voiceover1 or voiceover2');
      }

      Logger.info('Prompts and voiceovers generated successfully via OpenAI', {
        prompt1Length: parsedResponse.prompt1.length,
        prompt2Length: parsedResponse.prompt2.length,
        voiceover1Length: parsedResponse.voiceover1.length,
        voiceover2Length: parsedResponse.voiceover2.length,
      });

      return {
        prompt1: parsedResponse.prompt1,
        voiceover1: parsedResponse.voiceover1,
        prompt2: parsedResponse.prompt2,
        voiceover2: parsedResponse.voiceover2,
      };
    } catch (error) {
      Logger.error('Error generating prompts with OpenAI', error);
      throw new Error(`Failed to generate prompts: ${error.message}`);
    }
  }

  /**
   * Get aspect ratio specific guidance
   */
  getAspectRatioGuidance(aspectRatio) {
    const guidance = {
      landscape:
        'LANDSCAPE (16:9): Frame like YouTube/TikTok horizontal content. Device screen should dominate frame with person/hands visible. Over-shoulder laptop/phone view works great.',
      portrait:
        'PORTRAIT (9:16): Frame for TikTok/Instagram Reels vertical format. Phone screen fills most of frame, shot from above or straight-on. Perfect for phone-in-hand POV.',
      square:
        'SQUARE (1:1): Frame for Instagram feed. Center the device screen with balanced spacing. Good for product showcase centered in frame.',
    };

    return (
      guidance[aspectRatio] ||
      'Use wide cinematic framing optimized for landscape viewing.'
    );
  }
}

module.exports = new PromptGenerationService();
